### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by VirtualMagic** [The-Animonculory/Animonculory-Visual-Overhaul#10]
Tried to install the Mod Pack today und get the following in the Log:

1160,66 - Caught error getting disk info: Sequence contains no elements. Treating disk as Unspecified.
1160,66 - Hashing Remaining Archives
1160,66 - Looking for files to hash
1160,69 - Found 839 total files, 618 matching filesize
1160,74 - Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|skyrim_default.ini)
1160,74 - Cannot continue, was unable to download one or more archives
1160,75 - File hash check (-42) 148f87be46a5abcf1e19da00453cefb3ece2a3806a420c80259039b8dde01d1b
1160,79 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
1160,97 - File hash check (-42) 148f87be46a5abcf1e19da00453cefb3ece2a3806a420c80259039b8dde01d1b

It seems to be only thist file...

**Comment by VirtualMagic** [comment]
The problem seems to have been the game language. I simply set it to English for the purpose of testing, and it continued to run.

**Comment by chri3i** [comment]
there is no English for testing. too many things change with the language, so it's either english or a not working list

**Comment by VirtualMagic** [comment]
The only thing I did was to change Skyrim from German to English in Steam.... Then it worked immediately. That's all I can say about it. As long as the game runs in German, the installation does not work.

**Comment by chri3i** [comment]
yep, that's the same as i say. it will only work in English.
