### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by orcoth** [The-Animonculory/Animonculory-Visual-Overhaul#2]
When downloading, and installing the list with Wabbajack, I get this error in the log.

36976.49 - Loading ModLists from GitHub
36977.06 - Error downloading modlist image OME(FT)
36977.06 - Error downloading modlist image OME(FT)
36980.55 - Starting to install Animonculory Visual Overhaul
36980.57 - Starting Installer Task
36980.57 - Installation has Started
36980.57 - File hash check (-42) d828f2e002564a1ba81f1928aa3efbe24951d7d433976f21c5fb79d66a21322c
36980.91 - Configuring Processor
36980.91 - Install Folder: G:\Wabbajack-installs\Animonculory
36980.91 - Downloads Folder: X:\Wabbajack-download
36980.91 - Game Folder: G:\SteamLibrary\steamapps\common\Skyrim Special Edition
36980.91 - Wabbajack Folder: G:\Wabbajack\2.5.3.9
36980.91 - Drive watcher is starting. Will warn at 8GB and error at 4GB
36980.91 - Starting Drive watcher on G:\ currently 996.3GB free out of 1.8TB
36980.91 - Starting Drive watcher on X:\ currently 1.5TB free out of 1.8TB
36980.91 - Validating Game ESMs
36980.91 - Creating Output Folders
36981 - Optimizing ModList
36981 - Optimizing ModList directives
36981.96 - Looking for files to delete
36981.96 - Cleaning empty folders
36982.41 - Looking for unmodified files
36982.67 - Updating ModList
36982.67 - Optimized 65301 directives to 65301 required
36982.7 - Hashing Archives
36982.7 - Looking for files to hash
36982.82 - Found 1291 total files, 545 matching filesize
36982.96 - Downloading Missing Archives
36982.96 - Missing 1 archives
36982.96 - Getting Nexus API Key, if a browser appears, please accept
36982.96 - Loading server whitelist
36983.16 - Loaded permissions for 662 servers and 292 Google Drive files
36983.16 - Getting upgrades list
36983.19 - File hash check (-42) d828f2e002564a1ba81f1928aa3efbe24951d7d433976f21c5fb79d66a21322c
36983.26 - Downloading Skyrim_SkyrimPrefs.ini
36983.27 - Hashed download is incorrect
36983.27 - Loading for alternative to fiMS7vbbpNE=
36983.27 - No alternative for fiMS7vbbpNE= could be found
36983.33 - Hashing Remaining Archives
36983.33 - Looking for files to hash
36983.47 - Found 1291 total files, 545 matching filesize
36983.61 - Unable to download Skyrim_SkyrimPrefs.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|skyrim\skyrimprefs.ini)
36983.61 - Cannot continue, was unable to download one or more archives
36983.61 - File hash check (-42) d828f2e002564a1ba81f1928aa3efbe24951d7d433976f21c5fb79d66a21322c
36983.61 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in
![Skyrim_SkyrimPrefs ini](https://user-images.githubusercontent.com/62999316/158546010-5747e816-6d85-4bd0-9cbe-d59916248531.gif)
 C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
36984.12 - File hash check (-42) d828f2e002564a1ba81f1928aa3efbe24951d7d433976f21c5fb79d66a21322c

The downloded Skyrim_Skyrimprefs.ini is attached. (rename from .ini.gif to .ini

![Skyrim_SkyrimPrefs ini](https://user-images.githubusercontent.com/62999316/158546127-ba3e0c29-0e0c-474e-bb0f-fbe02b168ce8.gif)
)

**Comment by orcoth** [comment]
Not sure that the rename worked, complete file is here.

____________
[Display]
fShadowDistance=8000.0000
iNumFocusShadow=4
fInteriorShadowDistance=3000.0000
ffocusShadowMapDoubleEveryXUnit=450.0000
iShadowMapResolution=2048
fDynamicDOFBlurMultiplier=0.8000
fProjectedUVNormalDetailTilingScale=0.8000
fProjectedUVDiffuseNormalTilingScale=0.2000
bEnableProjecteUVDiffuseNormals=1
bUseTAA=1
bIndEnable=0
bSAO_CS_Enable=0
bToggleSparkles=1
bSAOEnable=1
bScreenSpaceReflectionEnabled=1
bIBLFEnable=1
bUse64bitsHDRRenderTarget=0
iSaveGameScreenShotHeighWSt=192
iSaveGameScreenShotWidthWS=320
iSaveGameScreenShotHeight=192
iSaveGameScreenShotWidth=256
iShadowMaskQuarter=4
bVolumetricLightingEnable=1
iVolumetricLightingQuality=1
bEnableImprovedSnow=1
fLightLODStartFade=3500.0000
bFXAAEnabled=0
fLeafAnimDampenDistEnd=4600.0000
fLeafAnimDampenDistStart=3600.0000
fTreesMidLODSwitchDist=9999999.0000
fMeshLODFadePercentDefault=1.2000
fMeshLODFadeBoundDefault=256.0000
fMeshLODLevel2FadeTreeDistance=2048.0000
fMeshLODLevel1FadeTreeDistance=2844.0000
fMeshLODLevel2FadeDist=9999999.0000
fMeshLODLevel1FadeDist=9999999.0000
fGamma=1.0000
bBorderless=0
bFull Screen=1
iSize H=1080
iSize W=2560
iScreenShotIndex=0
bTreesReceiveShadows=1
bUsePrecipitationOcclusion=1
bDrawLandShadows=0
iMaxSkinDecalsPerFrame=25
iMaxDecalsPerFrame=100
[Imagespace]
bDoDepthOfField=1
bLensFlare=1
[General]
fLightingOutputColourClampPostSpec=1.0000
fLightingOutputColourClampPostEnv=1.0000
fLightingOutputColourClampPostLit=1.0000
iStoryManagerLoggingEvent=-1
bEnableStoryManagerLogging=0
[MAIN]
fSkyCellRefFadeDistance=150000.0000
bGamepadEnable=1
bCrosshairEnabled=1
fHUDOpacity=1.0000
bSaveOnPause=0
bSaveOnTravel=1
bSaveOnWait=1
bSaveOnRest=1
[Interface]
fMouseCursorSpeed=1.0000
bDialogueSubtitles=0
bGeneralSubtitles=0
bShowCompass=1
[GamePlay]
bShowFloatingQuestMarkers=1
bShowQuestMarkers=1
iDifficulty=2
[Controls]
fMouseHeadingSensitivity=0.0125
fGamepadHeadingSensitivity=0.6667
bAlwaysRunByDefault=1
bInvertYValues=0
bGamePadRumble=1
[Particles]
iMaxDesired=750
[SaveGame]
fAutosaveEveryXMins=15.0000
[AudioMenu]
fAudioMasterVolume=1.0000
fVal7=1.0000
uID7=0
fVal6=1.0000
uID6=0
fVal5=1.0000
uID5=0
fVal4=1.0000
uID4=0
fVal3=0.5000
uID3=466532
fVal2=0.8000
uID2=554685
fVal1=0.8000
uID1=1007612
fVal0=1.0000
uID0=94881
[Clouds]
fCloudLevel2Distance=262144.0000
fCloudLevel1Distance=32768.0000
fCloudLevel0Distance=16384.0000
fCloudNearFadeDistance=9000.0000
[Water]
bUseWaterDisplacements=1
bUseWaterRefractions=1
bUseWaterReflections=1
bUseWaterDepth=1
[TerrainManager]
fTreeLoadDistance=75000.0000
fBlockMaximumDistance=250000.0000
fBlockLevel1Distance=70000.0000
fBlockLevel0Distance=35000.0000
fSplitDistanceMult=1.5000
bShowLODInEditor=1
[NavMesh]
fObstacleAlpha=0.5000
fCoverSideHighAlpha=0.8000
fCoverSideLowAlpha=0.6500
fEdgeFullAlpha=1.0000
fEdgeHighAlpha=0.7500
fEdgeLowAlpha=0.5000
fTriangleFullAlpha=0.7000
fTriangleHighAlpha=0.3500
fTriangleLowAlpha=0.2000
fLedgeBoxHalfHeight=25.0000
fEdgeDistFromVert=10.0000
fEdgeThickness=10.0000
fPointSize=2.5000
[Trees]
bRenderSkinnedTrees=1
uiMaxSkinnedTreesToRender=40
[Grass]
fGrassStartFadeDistance=7000.0000
fGrassMaxStartFadeDistance=7000.0000
fGrassMinStartFadeDistance=0.0000
[Decals]
bSkinnedDecals=1
bDecals=1
uMaxSkinDecals=100
uMaxDecals=1000
[LOD]
fLODFadeOutMultSkyCell=1.0000
fLODFadeOutMultObjects=15.0000
fLODFadeOutMultItems=15.0000
fLODFadeOutMultActors=15.0000
