### ISSUE TITLE
Wabbajack download not working

### ISSUE THREAD

**Issue by Fijutsi** [The-Animonculory/Animonculory-Visual-Overhaul#7]
Hey, i think there is a problem with downloading AVO-AE on wabbajack?

Here is the log from wabbajack:
[Wabbajack.current.log](https://github.com/The-Animonculory/Animonculory-Visual-Overhaul/files/8934324/Wabbajack.current.log)

0,23 - Wabbajack Build - 69de8f0e7a23c1b163ca7d158eca963343da3432
0,23 - Running in C:\Games\Wabbajack
0,25 - Detected Windows Version: 10.0.19043.0
0,25 - System settings - (15,9GB RAM) (6,6GB Page), Display: 1920 x 1080 (3,9GB VRAM - VideoMemorySizeMb=10240)
0,25 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0,25 - Outside of standard install folder, not updating
0,26 - Steam: Found no Regex matches in Steam Config at c:/steamsse\config\config.vdf
0,27 - Steam: Found game Skyrim Special Edition: Creation Kit (1946180) at "C:\steamsse\steamapps\common\Skyrim Special Edition"
0,27 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\steamsse\steamapps\common\Steamworks Shared"
0,27 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "C:\steamsse\steamapps\common\Skyrim Special Edition"
0,27 - Steam: Found game Skyrim Special Edition: Creation Kit (1946180) at "c:/steamsse\steamapps\common\Skyrim Special Edition"
0,27 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/steamsse\steamapps\common\Steamworks Shared"
0,27 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "c:/steamsse\steamapps\common\Skyrim Special Edition"
0,27 - GOG: Found game Gwent (1971477531) at "e:\games\gwent"
0,32 - EpicGamesStore: Found game Anno 1800 at "E:\Games\ANNO1800"
0,32 - EpicGamesStore: Found game ANNO 1800 Beta at "C:\Program Files\Epic Games\ANNO1800Beta"
0,32 - EpicGamesStore: Found game Satisfactory Early Access at "E:\Games\SatisfactoryEarlyAccess"
0,32 - EpicGamesStore: Found game Anno 1800 at "C:\Program Files\Epic Games\ANNO1800"
0,32 - EpicGamesStore: Found game Darkest Dungeon II at "E:\Games\DarkestDungeonII"
0,33 - Origin: Found no Ids and Paths in the MFST files
0,33 - Origin: Found no Ids for use with the Api
0,55 - Wabbajack Version: 2.5.3.22
0,9 - Build server is alive
0,9 - Build server is alive
0,9 - File hash check (-42) 1fc90d5d29859ec56b26c78424eec8d8684c603f02f1ff2dc2dcb699424cb5b6
0,9 - File hash check (-42) 1fc90d5d29859ec56b26c78424eec8d8684c603f02f1ff2dc2dcb699424cb5b6
2,24 - Loading ModLists from GitHub
12,17 - File hash check (-42) 1fc90d5d29859ec56b26c78424eec8d8684c603f02f1ff2dc2dcb699424cb5b6
12,27 - Starting Download of Animonculory/AVOAE
12,74 - CDN ERROR
12,75 - CDN ERROR
12,76 - CDN ERROR
12,79 - Wabbajack.Common.Exceptions.HttpException: Http Error NotFound - Not Found
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 23
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.GetWithRetry(Client client, String url) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 159
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.<>c__DisplayClass9_0.<<Download>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 109
...

**Comment by Althro** [comment]
Give it another try. I've just done a quick test on my end and it seems to be working now. If that fails, try enabling the Network Workaround in Wabbajack settings.
